# fly.toml app configuration file generated for synergy-discord on 2024-05-20T14:08:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'synergy-discord'
primary_region = 'arn'

[build]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
